### ISSUE TITLE
Move secure vault from kernel to a separate repo

### ISSUE THREAD

**Issue by laki88** [wso2/carbon-secvault#2]
Previously secure vault is in [carbon kernel](https://github.com/wso2/carbon-kernel/). It was tightly coupled with OSGI context. It was suggested to secure vault should support for both OSGI and non-OSGI mode. So remove secure vault from carbon kernel and move to a separate repo and make the necessary changes for non-OSGI support.

**Comment by Niranjan-K** [comment]
We need to also include this component as a feature so that it can be install using carbon-feature-plugin.

**Comment by Niranjan-K** [comment]
In-addition, the configuration files should be specific to each runtime, i.e., it should be in <CarbonHome>/wso2/<runtime>/conf

**Comment by Niranjan-K** [comment]
Closing since some initial PR #5 is merged. Creating a separate PR #7 to fix the issues and pending changes.
